networks:
  shared_network:
    driver: bridge

services:
  redis:
    image: 'redis:latest'
    container_name: "redis"
    restart: always
    command: redis-server --appendonly yes
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - shared_network


  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT}:15672'
    networks:
      - shared_network


  elasticsearch:
    image: 'elasticsearch:8.17.1'
    container_name: "elasticsearch"
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ports:
      - '${ELASTICSEARCH_PORT}:9200'
    networks:
      - shared_network


  kibana:
    image: 'docker.elastic.co/kibana/kibana:8.17.1'
    container_name: "kibana"
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - '${KIBANA_PORT}:5601'
    depends_on:
      - elasticsearch
    networks:
      - shared_network

